#!/bin/zsh

alias mv="mv -i"
alias py="python3"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias clear="clear; clear"
alias rsync="rsync -azh --progress"
alias fox="open -na Firefox"
alias gperf="/opt/homebrew/bin/gperf"
if [[ "$OSTYPE" == "darwin"* ]]; then
  alias finder="open -R ."
fi
alias chatgpt="OPENAI_API_KEY=\$(cred chatgpt-cli) chatgpt"

whereami() {
  echo $(whoami)@$(hostname):$(pwd)
}

# fzf() {
#   local dir
#   dir="$(/opt/homebrew/bin/fzf)"
#   if [[ -n "$dir" ]]; then
#     cd "$(dirname "$dir")" || return 1
#   fi
# }

source() {
  if [[ $# -eq 0 ]]; then
    builtin source ~/.zshrc
  else
    builtin source "$@"
  fi
}

png() {
  if ! command -v magick &> /dev/null; then
    echo "Error: imagemagick is not installed." >&2
    return 1
  fi
  local file="$1"
  magick -quality 100 -density 600 "$file" "${file%.*}.png"
}

user() {
  if ! command -v op &> /dev/null; then
    echo "error: 1password CLI is not installed." >&2
    return 1
  fi
  op item get "$1" --field username
}

pswd() {
  if ! command -v op &> /dev/null; then
    echo "error: 1password CLI is not installed." >&2
    return 1
  fi
  op item get "$1" --field password
}

cred() {
  if ! command -v op &> /dev/null; then
    echo "error: 1password CLI is not installed." >&2
    return 1
  fi
  op item get "$1" --field credential
}

sherlock() {
  username=$(user stanford)
  password=$(pswd stanford)
  expect -c "
  log_user 0
  spawn ssh $username@login.sherlock.stanford.edu
  expect \"$username@login.sherlock.stanford.edu's password:\"
  send \"$password\r\"
  expect \"Enter a passcode or select one of the following options:\"
  send \"1\r\"
  interact
  "
}

imp() {
  username=$(user imp)
  password=$(pswd imp)
  sshpass -p "$password" ssh $username@imp
}

ssh-terminfo() {
  infocmp -x | ssh "$1" 'mkdir -p ~/.terminfo && tic -x -'
  ssh "$1" 'grep -qF "resize()" ~/.bashrc 2>/dev/null || cat >> ~/.bashrc << '\''EOF'\''
resize() {
  old=$(stty -g)
  stty raw -echo min 0 time 5
  printf '\''\033[18t'\'' > /dev/tty
  IFS='\'';t'\'' read -r _ rows cols _ < /dev/tty
  stty "$old"
  stty cols "$cols" rows "$rows"
}
EOF'
}

resize() {
  old=$(stty -g)
  stty raw -echo min 0 time 5
  printf '\033[18t' > /dev/tty
  IFS=';t' read -r _ rows cols _ < /dev/tty
  stty "$old"
  stty cols "$cols" rows "$rows"
}

