#!/usr/bin/env zsh

if [[ -x "$LOCAL_PREFIX/bin/oh-my-posh" ]] || command -v oh-my-posh &> /dev/null; then
    return 0 2>/dev/null || exit 0
fi

mkdir -p "$LOCAL_PREFIX/bin"
curl -s https://ohmyposh.dev/install.sh | bash -s -- -d "$LOCAL_PREFIX/bin"
