#!/usr/bin/env zsh

ZSH_PLUGIN_DIR="$HOME/.config/zsh"
mkdir -p "$ZSH_PLUGIN_DIR"

if [[ ! -d "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting" ]]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
        "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting"
else
    (cd "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting" && git pull --quiet 2>/dev/null &)
fi

if [[ ! -d "$ZSH_PLUGIN_DIR/zsh-autosuggestions" ]]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions.git \
        "$ZSH_PLUGIN_DIR/zsh-autosuggestions"
else
    (cd "$ZSH_PLUGIN_DIR/zsh-autosuggestions" && git pull --quiet 2>/dev/null &)
fi
